// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CacheProject.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 1",
                            Price = 100.99m,
                            Sku = "SKU-00001",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 2",
                            Price = 101.99m,
                            Sku = "SKU-00002",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 3",
                            Price = 102.99m,
                            Sku = "SKU-00003",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 4",
                            Price = 103.99m,
                            Sku = "SKU-00004",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 5",
                            Price = 104.99m,
                            Sku = "SKU-00005",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 6",
                            Price = 105.99m,
                            Sku = "SKU-00006",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 7",
                            Price = 106.99m,
                            Sku = "SKU-00007",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 8",
                            Price = 107.99m,
                            Sku = "SKU-00008",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 9",
                            Price = 108.99m,
                            Sku = "SKU-00009",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 10",
                            Price = 109.99m,
                            Sku = "SKU-00010",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 11",
                            Price = 110.99m,
                            Sku = "SKU-00011",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 12",
                            Price = 111.99m,
                            Sku = "SKU-00012",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 13",
                            Price = 112.99m,
                            Sku = "SKU-00013",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 14",
                            Price = 113.99m,
                            Sku = "SKU-00014",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 15",
                            Price = 114.99m,
                            Sku = "SKU-00015",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 16",
                            Price = 115.99m,
                            Sku = "SKU-00016",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 17",
                            Price = 116.99m,
                            Sku = "SKU-00017",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 18",
                            Price = 117.99m,
                            Sku = "SKU-00018",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 19",
                            Price = 118.99m,
                            Sku = "SKU-00019",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 20",
                            Price = 119.99m,
                            Sku = "SKU-00020",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 21",
                            Price = 120.99m,
                            Sku = "SKU-00021",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 22",
                            Price = 121.99m,
                            Sku = "SKU-00022",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 23",
                            Price = 122.99m,
                            Sku = "SKU-00023",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 24",
                            Price = 123.99m,
                            Sku = "SKU-00024",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 25",
                            Price = 124.99m,
                            Sku = "SKU-00025",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 26",
                            Price = 125.99m,
                            Sku = "SKU-00026",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 27",
                            Price = 126.99m,
                            Sku = "SKU-00027",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 28",
                            Price = 127.99m,
                            Sku = "SKU-00028",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 29",
                            Price = 128.99m,
                            Sku = "SKU-00029",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 30",
                            Price = 129.99m,
                            Sku = "SKU-00030",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 31",
                            Price = 130.99m,
                            Sku = "SKU-00031",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 32",
                            Price = 131.99m,
                            Sku = "SKU-00032",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 33",
                            Price = 132.99m,
                            Sku = "SKU-00033",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 34",
                            Price = 133.99m,
                            Sku = "SKU-00034",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 35",
                            Price = 134.99m,
                            Sku = "SKU-00035",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 36",
                            Price = 135.99m,
                            Sku = "SKU-00036",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 37",
                            Price = 136.99m,
                            Sku = "SKU-00037",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 38",
                            Price = 137.99m,
                            Sku = "SKU-00038",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 39",
                            Price = 138.99m,
                            Sku = "SKU-00039",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 40",
                            Price = 139.99m,
                            Sku = "SKU-00040",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 41",
                            Price = 140.99m,
                            Sku = "SKU-00041",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 42",
                            Price = 141.99m,
                            Sku = "SKU-00042",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 43",
                            Price = 142.99m,
                            Sku = "SKU-00043",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 44",
                            Price = 143.99m,
                            Sku = "SKU-00044",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 45",
                            Price = 144.99m,
                            Sku = "SKU-00045",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 46",
                            Price = 145.99m,
                            Sku = "SKU-00046",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 47",
                            Price = 146.99m,
                            Sku = "SKU-00047",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 48",
                            Price = 147.99m,
                            Sku = "SKU-00048",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 49",
                            Price = 148.99m,
                            Sku = "SKU-00049",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 50",
                            Price = 149.99m,
                            Sku = "SKU-00050",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 51",
                            Price = 150.99m,
                            Sku = "SKU-00051",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 52",
                            Price = 151.99m,
                            Sku = "SKU-00052",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 53",
                            Price = 152.99m,
                            Sku = "SKU-00053",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 54",
                            Price = 153.99m,
                            Sku = "SKU-00054",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 55",
                            Price = 154.99m,
                            Sku = "SKU-00055",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 56",
                            Price = 155.99m,
                            Sku = "SKU-00056",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 57",
                            Price = 156.99m,
                            Sku = "SKU-00057",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 58",
                            Price = 157.99m,
                            Sku = "SKU-00058",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 59",
                            Price = 158.99m,
                            Sku = "SKU-00059",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 60",
                            Price = 159.99m,
                            Sku = "SKU-00060",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 61",
                            Price = 160.99m,
                            Sku = "SKU-00061",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 62",
                            Price = 161.99m,
                            Sku = "SKU-00062",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 63",
                            Price = 162.99m,
                            Sku = "SKU-00063",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 64",
                            Price = 163.99m,
                            Sku = "SKU-00064",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 65",
                            Price = 164.99m,
                            Sku = "SKU-00065",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 66",
                            Price = 165.99m,
                            Sku = "SKU-00066",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 67",
                            Price = 166.99m,
                            Sku = "SKU-00067",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 68",
                            Price = 167.99m,
                            Sku = "SKU-00068",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 69",
                            Price = 168.99m,
                            Sku = "SKU-00069",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 70",
                            Price = 169.99m,
                            Sku = "SKU-00070",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 71",
                            Price = 170.99m,
                            Sku = "SKU-00071",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 72",
                            Price = 171.99m,
                            Sku = "SKU-00072",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 73",
                            Price = 172.99m,
                            Sku = "SKU-00073",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 74",
                            Price = 173.99m,
                            Sku = "SKU-00074",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 75",
                            Price = 174.99m,
                            Sku = "SKU-00075",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 76",
                            Price = 175.99m,
                            Sku = "SKU-00076",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 77",
                            Price = 176.99m,
                            Sku = "SKU-00077",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 78",
                            Price = 177.99m,
                            Sku = "SKU-00078",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 79",
                            Price = 178.99m,
                            Sku = "SKU-00079",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 80",
                            Price = 179.99m,
                            Sku = "SKU-00080",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 81",
                            Price = 180.99m,
                            Sku = "SKU-00081",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 82",
                            Price = 181.99m,
                            Sku = "SKU-00082",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 83",
                            Price = 182.99m,
                            Sku = "SKU-00083",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 84",
                            Price = 183.99m,
                            Sku = "SKU-00084",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 85",
                            Price = 184.99m,
                            Sku = "SKU-00085",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 86",
                            Price = 185.99m,
                            Sku = "SKU-00086",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 87",
                            Price = 186.99m,
                            Sku = "SKU-00087",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 88",
                            Price = 187.99m,
                            Sku = "SKU-00088",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 89",
                            Price = 188.99m,
                            Sku = "SKU-00089",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 90",
                            Price = 189.99m,
                            Sku = "SKU-00090",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 91",
                            Price = 190.99m,
                            Sku = "SKU-00091",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 92",
                            Price = 191.99m,
                            Sku = "SKU-00092",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 93",
                            Price = 192.99m,
                            Sku = "SKU-00093",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 94",
                            Price = 193.99m,
                            Sku = "SKU-00094",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 95",
                            Price = 194.99m,
                            Sku = "SKU-00095",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 96",
                            Price = 195.99m,
                            Sku = "SKU-00096",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 97",
                            Price = 196.99m,
                            Sku = "SKU-00097",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 98",
                            Price = 197.99m,
                            Sku = "SKU-00098",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 99",
                            Price = 198.99m,
                            Sku = "SKU-00099",
                            StockQuantity = 1000
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Demo Product 100",
                            Price = 199.99m,
                            Sku = "SKU-00100",
                            StockQuantity = 1000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
